#!/usr/bin/env python3
"""
Parses contribution files and produces a structured summary of the project's evolution.

Usage: python tools/contribution_reader.py
Reads all contributions/PR_DESCRIPTION_*.md files and writes EVOLUTION.md to the repo root.

Future agents: run this from the repo root after adding a new contribution file to keep
EVOLUTION.md current. It is a compressed history designed to save context for future readers.
"""

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class Contribution:
    number: int
    filename: str
    agent: Optional[str] = None
    date: Optional[str] = None
    pr: Optional[str] = None
    sections: dict = field(default_factory=dict)
    raw: str = ""


def parse_contribution(path: Path) -> Contribution:
    text = path.read_text(encoding="utf-8")

    match = re.search(r"PR_DESCRIPTION_(\d+)\.md", path.name)
    number = int(match.group(1)) if match else 0

    c = Contribution(number=number, filename=path.name, raw=text)

    for field_name in ("Agent", "Date", "PR"):
        m = re.search(rf"\*\*{field_name}:\*\*\s*(.+?)(?:\n|$)", text)
        if m:
            setattr(c, field_name.lower(), m.group(1).strip())

    # Split on ## headers; parts alternates [preamble, header, content, header, content, ...]
    parts = re.split(r"\n## (.+)\n", text)
    for i in range(1, len(parts) - 1, 2):
        header = parts[i].strip()
        content = parts[i + 1].strip()
        # Trim trailing --- separators and italic footnotes
        content = re.sub(r"\n---.*$", "", content, flags=re.DOTALL).strip()
        c.sections[header] = content

    return c


def load_all(contributions_dir: Path) -> list[Contribution]:
    files = sorted(contributions_dir.glob("PR_DESCRIPTION_*.md"))
    return [parse_contribution(f) for f in files]


def generate_evolution(contributions: list[Contribution]) -> str:
    lines = [
        "# EVOLUTION.md",
        "",
        "> Auto-generated by `tools/contribution_reader.py`. Do not edit by hand.",
        "> Run the script from the repo root to regenerate after each new contribution.",
        "",
        f"**Total contributions:** {len(contributions)}",
        "",
        "---",
        "",
    ]

    for c in contributions:
        lines.append(f"## Contribution #{c.number:03d}")
        if c.agent:
            lines.append(f"- **Agent:** {c.agent}")
        if c.date:
            lines.append(f"- **Date:** {c.date}")
        if c.pr:
            lines.append(f"- **PR:** {c.pr}")
        lines.append("")

        for header, content in c.sections.items():
            lines.append(f"**{header}:**")
            lines.append("")
            lines.append(content)
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    repo_root = Path(__file__).parent.parent
    contributions_dir = repo_root / "contributions"
    output_path = repo_root / "EVOLUTION.md"

    contributions = load_all(contributions_dir)
    summary = generate_evolution(contributions)
    output_path.write_text(summary, encoding="utf-8")
    print(f"Generated {output_path} ({len(contributions)} contribution(s)).")
