#!/usr/bin/env python3
"""
Generates SNAPSHOT.md — a structural view of the project's current state.

While EVOLUTION.md documents what happened (contribution history), SNAPSHOT.md
describes what is: the modules that exist, what they export, how many tests cover
them, and whether the CI pipeline is in place.

This is distinct from and complementary to EVOLUTION.md. A future agent reading
SNAPSHOT.md understands the codebase structure immediately, without reading every
file. A future agent reading EVOLUTION.md understands the decisions that produced it.

Usage: python tools/project_snapshot.py
Writes SNAPSHOT.md to the repo root.
"""

import ast
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


@dataclass
class ModuleInfo:
    path: str
    docstring: Optional[str]
    functions: List[str]
    classes: List[str]
    lines: int


@dataclass
class TestInfo:
    path: str
    test_functions: List[str]


def analyze_python_file(path: Path) -> ModuleInfo:
    """Parse a Python file and extract top-level structure via ast."""
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)

    docstring = ast.get_docstring(tree)

    # Only top-level definitions — not nested functions or class methods
    functions = [
        node.name
        for node in tree.body
        if isinstance(node, ast.FunctionDef) and not node.name.startswith("_")
    ]
    classes = [
        node.name for node in tree.body if isinstance(node, ast.ClassDef)
    ]

    return ModuleInfo(
        path=str(path),
        docstring=docstring,
        functions=functions,
        classes=classes,
        lines=len(source.splitlines()),
    )


def find_test_functions(path: Path) -> TestInfo:
    """Extract test function names from a test file."""
    source = path.read_text(encoding="utf-8")
    tree = ast.parse(source)

    test_fns = [
        node.name
        for node in ast.walk(tree)
        if isinstance(node, ast.FunctionDef) and node.name.startswith("test_")
    ]

    return TestInfo(path=str(path), test_functions=test_fns)


def scan_tools(tools_dir: Path) -> List[ModuleInfo]:
    files = [f for f in sorted(tools_dir.glob("*.py")) if f.name != "__init__.py"]
    return [analyze_python_file(f) for f in files]


def scan_tests(tests_dir: Path) -> List[TestInfo]:
    files = sorted(tests_dir.glob("test_*.py"))
    return [find_test_functions(f) for f in files]


def count_contributions(contributions_dir: Path) -> int:
    return len(list(contributions_dir.glob("PR_DESCRIPTION_*.md")))


def generate_snapshot(
    tools_modules: List[ModuleInfo],
    test_files: List[TestInfo],
    num_contributions: int,
    has_workflow: bool,
) -> str:
    total_tests = sum(len(t.test_functions) for t in test_files)

    lines = [
        "# SNAPSHOT.md",
        "",
        "> Auto-generated by `tools/project_snapshot.py`. Do not edit by hand.",
        "> Run the script from the repo root to regenerate after significant changes.",
        "",
        "A structural view of the project's current state.",
        "For the history of contributions, see [docs/EVOLUTION.md](docs/EVOLUTION.md).",
        "",
        "---",
        "",
        "## Architecture",
        "",
        "- **Language:** Python",
        f"- **Contributions documented:** {num_contributions}",
        f"- **CI workflow:** {'present' if has_workflow else 'absent'}",
        f"- **Total test functions:** {total_tests}",
        "",
    ]

    lines += [
        "## Tools",
        "",
    ]

    for m in tools_modules:
        rel_path = Path(m.path).name
        lines.append(f"### `tools/{rel_path}`")
        lines.append("")
        if m.docstring:
            first_line = m.docstring.strip().splitlines()[0]
            lines.append(first_line)
            lines.append("")
        if m.classes:
            lines.append(f"**Classes:** {', '.join(f'`{c}`' for c in m.classes)}")
        if m.functions:
            lines.append(
                f"**Public functions:** {', '.join(f'`{f}`' for f in m.functions)}"
            )
        lines.append(f"**Lines:** {m.lines}")
        lines.append("")

    lines += [
        "## Tests",
        "",
    ]

    for t in test_files:
        rel_path = Path(t.path).name
        lines.append(f"### `tests/{rel_path}`")
        lines.append("")
        if t.test_functions:
            for fn in t.test_functions:
                lines.append(f"- `{fn}`")
        else:
            lines.append("*(no test functions found)*")
        lines.append("")

    lines += [
        "---",
        "",
        "> SNAPSHOT.md reflects only the structure visible at generation time.",
        "> Run `python tools/project_snapshot.py` to update after changes.",
    ]

    return "\n".join(lines)


if __name__ == "__main__":
    repo_root = Path(__file__).parent.parent

    tools_modules = scan_tools(repo_root / "tools")
    test_files = scan_tests(repo_root / "tests")
    num_contributions = count_contributions(repo_root / "contributions")
    has_workflow = (repo_root / ".github" / "workflows" / "pr-review.yml").exists()

    snapshot = generate_snapshot(tools_modules, test_files, num_contributions, has_workflow)

    output_path = repo_root / "docs" / "SNAPSHOT.md"
    output_path.write_text(snapshot, encoding="utf-8")
    print(f"Generated {output_path}.")
