#!/usr/bin/env python3
"""
Generates THREADS.md — open questions and unfinished work raised by contributions.

Scans contributions/PR_DESCRIPTION_*.md for an optional "## Open threads" section and
aggregates the bullet items as individual threads. Each thread is tagged with the
contribution number that raised it.

While EVOLUTION.md describes what has happened (history) and SNAPSHOT.md describes
what is (structure), THREADS.md describes what remains — the forward edge of the
project, work that future agents may pick up.

Usage: python tools/thread_collector.py
Writes THREADS.md to the repo root.

Convention for future contributions: include an optional `## Open threads` section in
your PR description, with one Markdown bullet (`- ...`) per thread. Re-run this script
from the repo root to regenerate THREADS.md.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import List


@dataclass
class Thread:
    contribution_number: int
    text: str


def parse_open_threads(text: str) -> List[str]:
    """Extract bullet items from an `## Open threads` section, if present.

    Returns a list of thread bodies (one per top-level bullet). Each body may span
    multiple lines if the original bullet had indented continuation lines.
    """
    section_match = re.search(
        r"(?:^|\n)##\s+Open threads\s*\n(.+?)(?=\n##\s|\n---|\Z)",
        text,
        re.DOTALL | re.IGNORECASE,
    )
    if not section_match:
        return []

    section = section_match.group(1)
    bullets = re.findall(
        r"^\s*-\s+(.+?)(?=\n\s*-\s+|\Z)",
        section,
        re.MULTILINE | re.DOTALL,
    )
    return [b.strip() for b in bullets if b.strip()]


def collect_threads(contributions_dir: Path) -> List[Thread]:
    threads = []
    for f in sorted(contributions_dir.glob("PR_DESCRIPTION_*.md")):
        match = re.search(r"PR_DESCRIPTION_(\d+)\.md", f.name)
        if not match:
            continue
        number = int(match.group(1))
        text = f.read_text(encoding="utf-8")
        for body in parse_open_threads(text):
            threads.append(Thread(contribution_number=number, text=body))
    return threads


def generate_threads_md(threads: List[Thread]) -> str:
    lines = [
        "# THREADS.md",
        "",
        "> Auto-generated by `tools/thread_collector.py`. Do not edit by hand.",
        "> Run the script from the repo root to regenerate after a PR description adds or removes open threads.",
        "",
        "Open questions and unfinished work surfaced by contributions to this project.",
        "For history, see [EVOLUTION.md](EVOLUTION.md). For current structure, see [SNAPSHOT.md](SNAPSHOT.md).",
        "",
        "Each entry is tagged with the contribution number that raised it. A thread remains",
        "open until a future contribution explicitly addresses it.",
        "",
        f"**Total open threads:** {len(threads)}",
        "",
        "---",
        "",
    ]

    if not threads:
        lines.append("*No open threads recorded.*")
        return "\n".join(lines)

    for t in threads:
        lines.append(f"### From contribution #{t.contribution_number:03d}")
        lines.append("")
        for line in t.text.splitlines():
            lines.append(f"> {line}" if line.strip() else ">")
        lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    repo_root = Path(__file__).parent.parent
    contributions_dir = repo_root / "contributions"

    threads = collect_threads(contributions_dir)
    output = generate_threads_md(threads)

    output_path = repo_root / "THREADS.md"
    output_path.write_text(output, encoding="utf-8")
    print(f"Generated {output_path} ({len(threads)} thread(s)).")
