#!/usr/bin/env python3
"""
Generates THREADS.md — open questions and unfinished work raised by contributions.

Scans contributions/PR_DESCRIPTION_*.md for an optional "## Open threads" section and
aggregates the bullet items as individual threads. Each thread is tagged with the
contribution number that raised it.

While EVOLUTION.md describes what has happened (history) and SNAPSHOT.md describes
what is (structure), THREADS.md describes what remains — the forward edge of the
project, work that future agents may pick up.

Usage: python tools/thread_collector.py
Writes THREADS.md to the repo root.

Convention for future contributions: include an optional `## Open threads` section in
your PR description, with one Markdown bullet (`- ...`) per thread. Re-run this script
from the repo root to regenerate THREADS.md.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import List


@dataclass
class Thread:
    id: str  # e.g., "005:1"
    contribution_number: int
    index: int
    text: str


@dataclass
class Resolution:
    thread_id: str
    resolved_by: int
    reason: str


def parse_open_threads(text: str) -> List[str]:
    """Extract bullet items from an `## Open threads` section, if present.

    Returns a list of thread bodies (one per top-level bullet). Each body may span
    multiple lines if the original bullet had indented continuation lines.
    """
    section_match = re.search(
        r"(?:^|\n)##\s+Open threads\s*\n(.+?)(?=\n##\s|\n---|\Z)",
        text,
        re.DOTALL | re.IGNORECASE,
    )
    if not section_match:
        return []

    section = section_match.group(1)
    bullets = re.findall(
        r"^\s*-\s+(.+?)(?=\n\s*-\s+|\Z)",
        section,
        re.MULTILINE | re.DOTALL,
    )
    return [b.strip() for b in bullets if b.strip()]


def parse_resolved_threads(text: str, contribution_number: int) -> List[Resolution]:
    """Extract items from a `## Resolved threads` section, if present.

    Looks for bullets like `- #005:1 — reason`.
    """
    section_match = re.search(
        r"(?:^|\n)##\s+Resolved threads\s*\n(.+?)(?=\n##\s|\n---|\Z)",
        text,
        re.DOTALL | re.IGNORECASE,
    )
    if not section_match:
        return []

    resolutions = []
    section = section_match.group(1)
    for line in section.splitlines():
        line = line.strip()
        if not line:
            continue
        # match `- #005:1` or `- 005:1` followed optionally by ` - Reason` or ` — Reason`
        m = re.match(r"^\s*-\s+#?(\d+):(\d+)(?:\s+(?:-|—)\s+(.*))?", line)
        if m:
            cat_num, idx_num, reason = m.groups()
            thread_id = f"{int(cat_num):03d}:{int(idx_num)}"
            resolutions.append(Resolution(
                thread_id=thread_id,
                resolved_by=contribution_number,
                reason=reason.strip() if reason else ""
            ))
    return resolutions


def collect_threads(contributions_dir: Path) -> tuple[List[Thread], List[Resolution]]:
    threads = []
    resolutions = []
    
    for f in sorted(contributions_dir.glob("PR_DESCRIPTION_*.md")):
        match = re.search(r"PR_DESCRIPTION_(\d+)\.md", f.name)
        if not match:
            continue
        number = int(match.group(1))
        text = f.read_text(encoding="utf-8")
        
        parsed_threads = parse_open_threads(text)
        for i, body in enumerate(parsed_threads, start=1):
            thread_id = f"{number:03d}:{i}"
            threads.append(Thread(
                id=thread_id,
                contribution_number=number,
                index=i,
                text=body
            ))
            
        parsed_resolutions = parse_resolved_threads(text, number)
        resolutions.extend(parsed_resolutions)
        
    return threads, resolutions


def generate_threads_md(threads: List[Thread], resolutions: List[Resolution]) -> str:
    lines = [
        "# THREADS.md",
        "",
        "> Auto-generated by `tools/thread_collector.py`. Do not edit by hand.",
        "> Run the script from the repo root to regenerate after a PR description adds or removes open threads.",
        "",
        "Open questions and unfinished work surfaced by contributions to this project.",
        "For history, see [docs/EVOLUTION.md](docs/EVOLUTION.md). For current structure, see [docs/SNAPSHOT.md](docs/SNAPSHOT.md).",
        "",
        "Each entry is tagged with the contribution number that raised it. A thread remains",
        "open until a future contribution explicitly addresses it in a `## Resolved threads` section.",
        "",
    ]
    
    resolved_ids_map = {res.thread_id: res for res in resolutions}
    
    open_threads = [t for t in threads if t.id not in resolved_ids_map]
    resolved_threads = [t for t in threads if t.id in resolved_ids_map]
    
    lines.append(f"**Total open threads:** {len(open_threads)}")
    if resolved_threads:
        lines.append(f"**Total resolved threads:** {len(resolved_threads)}")
    lines.append("")
    lines.append("---")
    lines.append("")
    
    lines.append("## Open threads")
    lines.append("")
    if not open_threads:
        lines.append("*No open threads recorded.*")
    else:
        for t in open_threads:
            lines.append(f"### #{t.id} (From contribution #{t.contribution_number:03d})")
            lines.append("")
            for line in t.text.splitlines():
                lines.append(f"> {line}" if line.strip() else ">")
            lines.append("")

    if resolved_threads:
        lines.append("---")
        lines.append("")
        lines.append("## Resolved threads")
        lines.append("")
        for t in resolved_threads:
            res = resolved_ids_map[t.id]
            lines.append(f"### ~#{t.id}~ (Resolved in #{res.resolved_by:03d})")
            lines.append("")
            for line in t.text.splitlines():
                lines.append(f"> {line}" if line.strip() else ">")
            lines.append(">")
            if res.reason:
                lines.append(f"> **Resolution:** {res.reason}")
            else:
                lines.append(f"> **Resolution:** Addressed in #{res.resolved_by:03d}")
            lines.append("")

    return "\n".join(lines).strip() + "\n"


if __name__ == "__main__":
    repo_root = Path(__file__).parent.parent
    contributions_dir = repo_root / "contributions"

    threads, resolutions = collect_threads(contributions_dir)
    output = generate_threads_md(threads, resolutions)

    output_path = repo_root / "docs" / "THREADS.md"
    output_path.write_text(output, encoding="utf-8")
    
    resolved_count = len([t for t in threads if t.id in {r.thread_id for r in resolutions}])
    open_count = len(threads) - resolved_count
    
    print(f"Generated {output_path} ({open_count} open thread(s), {resolved_count} resolved).")
